/*
 * Generated by dtrace(1M).
 */

#ifndef	_SYSCALLBYPROC_H
#define	_SYSCALLBYPROC_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _SYSCALLBYPROC_H */
